# Generated by Django 5.2.7 on 2025-10-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название ресторана", max_length=255, verbose_name="Название ресторана"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Введите адрес ресторана", max_length=500, verbose_name="Адрес ресторана"
                    ),
                ),
                ("contact_info", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Внесите краткое описание ресторана",
                        null=True,
                        verbose_name="Описание ресторана",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Загрузите фото ресторана",
                        upload_to="restaurant/photo",
                        verbose_name="Фото ресторана",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресторан",
                "verbose_name_plural": "Рестораны",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "number",
                    models.CharField(help_text="Укажите номер стола", max_length=50, verbose_name="Номер стола"),
                ),
                ("size", models.PositiveIntegerField(help_text="Количество мест за столиком")),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="reservations.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
                "ordering": ["size"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_name", models.CharField(max_length=255, verbose_name="Имя клиента")),
                ("telephone", models.CharField(max_length=255, verbose_name="Телефон клиента")),
                ("number_of_guests", models.PositiveIntegerField(help_text="Количество гостей")),
                ("reservation_date", models.DateField(help_text="Дата брони")),
                ("reservation_start", models.TimeField(help_text="Время начала брони")),
                ("reservation_and", models.TimeField(help_text="Время окончания брони")),
                (
                    "status",
                    models.CharField(
                        choices=[("confirmed", "Подтверждено"), ("cancelled", "Отменено"), ("pending", "В ожидании")],
                        default="pending",
                        help_text="Статус брони",
                        max_length=20,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="reservations.restaurant",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="reservations.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронь>",
                "verbose_name_plural": "Брони",
                "ordering": ["reservation_date", "reservation_start"],
            },
        ),
    ]
