# Generated by Django 5.2.7 on 2025-10-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="contact_info",
            field=models.CharField(default="", max_length=255, verbose_name="Телефон ресторана"),
            preserve_default=False,
        ),
    ]
