# Generated by Django 5.2.7 on 2025-10-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_alter_restaurant_contact_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="seating_plan_image",
            field=models.ImageField(
                default="seating_plans/photo/default.jpg",
                help_text="Загрузите план рассадки",
                upload_to="seating_plans/photo",
                verbose_name="План рассадки",
            ),
        ),
    ]
