# Generated by Django 5.2.7 on 2025-10-12 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_remove_reservation_seating_plan_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="location",
        ),
        migrations.AlterField(
            model_name="reservation",
            name="number_of_guests",
            field=models.PositiveIntegerField(help_text="Количество гостей", verbose_name="Количество гостей"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_and",
            field=models.TimeField(help_text="Время окончания брони", verbose_name="Время окончания брони"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateField(help_text="Дата брони", verbose_name="Дата брони"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_start",
            field=models.TimeField(help_text="Время начала брони", verbose_name="Время начала брони"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservations.restaurant",
                verbose_name="Ресторан",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[("confirmed", "Подтверждено"), ("cancelled", "Отменено"), ("pending", "В ожидании")],
                default="pending",
                help_text="Статус брони",
                max_length=20,
                verbose_name="Статус брони",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservations.table",
                verbose_name="Номер стола",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="restaurant",
            field=models.ForeignKey(
                help_text="Выбрать ресторан",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tables",
                to="reservations.restaurant",
                verbose_name="Ресторан",
            ),
        ),
        migrations.AlterField(
            model_name="table",
            name="size",
            field=models.PositiveIntegerField(help_text="Количество мест за столиком", verbose_name="Кол-во мест"),
        ),
    ]
