# Generated by Django 5.2.7 on 2025-10-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_remove_table_location_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={"ordering": ["restaurant", "size"], "verbose_name": "Стол", "verbose_name_plural": "Столы"},
        ),
    ]
