# Generated by Django 5.2.7 on 2025-10-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_alter_table_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_and",
            field=models.TimeField(
                blank=True, help_text="Время окончания брони", null=True, verbose_name="Время окончания брони"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateField(blank=True, help_text="Дата брони", null=True, verbose_name="Дата брони"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_start",
            field=models.TimeField(
                blank=True, help_text="Время начала брони", null=True, verbose_name="Время начала брони"
            ),
        ),
    ]
