# Generated by Django 5.2.7 on 2025-10-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_alter_reservation_reservation_and_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="original_reservation_and",
            field=models.TimeField(blank=True, null=True, verbose_name="Время окончания (оригинальное)"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="original_reservation_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата бронирования (оригинальная)"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="original_reservation_start",
            field=models.TimeField(blank=True, null=True, verbose_name="Время начала (оригинальное)"),
        ),
    ]
