# Generated by Django 5.2.7 on 2025-10-16 15:42

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0008_reservation_original_reservation_and_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="RU", verbose_name="Телефон клиента"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="contact_info",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="RU", verbose_name="Телефон ресторана"
            ),
        ),
    ]
