# Generated by Django 5.2.7 on 2025-10-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0010_reservation_owner_restaurant_owner_table_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["reservation_date", "reservation_start"],
                "permissions": [
                    ("can_change_reservation", "Может редактировать бронь"),
                    ("can_view_reservations", "Может просматривать брони своего ресторана"),
                    ("can_delete_reservations", "Может удалить бронь"),
                ],
                "verbose_name": "Бронь>",
                "verbose_name_plural": "Брони",
            },
        ),
        migrations.AlterModelOptions(
            name="restaurant",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_edit_restaurant", "Может редактировать свой ресторан"),
                    ("can_delete_restaurant", "Может удалить свой ресторан"),
                    ("can_add_restaurant", "Может создать ресторан"),
                ],
                "verbose_name": "Ресторан",
                "verbose_name_plural": "Рестораны",
            },
        ),
        migrations.AlterModelOptions(
            name="table",
            options={
                "ordering": ["restaurant", "size"],
                "permissions": [
                    ("can_view_table", "Может просматривать список своих столов"),
                    ("can_delete_table", "Может удалить свой стол"),
                    ("can_add_table", "Может создать стол"),
                    ("can_edit_table", "Может редактировать свой стол"),
                ],
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
            },
        ),
    ]
