# Generated by Django 5.2.7 on 2025-10-20 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0011_alter_reservation_options_alter_restaurant_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_restaurants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Менеджер",
            ),
        ),
    ]
