# Generated by Django 5.2.7 on 2025-10-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0012_restaurant_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="note",
            field=models.TextField(
                blank=True, help_text="Дополнительная информация о бронировании", null=True, verbose_name="Примечание"
            ),
        ),
    ]
